### ISSUE TITLE
sidebar-off-canvas behaves strangely

### ISSUE THREAD

**Issue by dacodekid** [coreui/coreui-free-bootstrap-admin-template#214]
I have a `sidebar` with a combination of `sidebar-hidden` & `sidebar-off-canvas` classes. 

1. When the `sidebar` is expanded (by clicking the burger icon), and screen size reduced to mobile size, the sidebar hides fine.

2. But if the `sidebar` is NOT expanded and the page shrinks, I see about 20 pixels of sidebar shown (believe, this is due to `$sidebar-width` being used against `$mobile-sidebar-width`)

![image](https://user-images.githubusercontent.com/10047844/28624221-786a98ca-71e6-11e7-85e1-77eda918635f.png)

3. Also, `sidebar-off-canvas` is pushing the components to the right, instead overlaying them.
![image](https://user-images.githubusercontent.com/10047844/28625612-d2b50096-71ea-11e7-9391-3f6121c756c9.png)

**Comment by dacodekid** [comment]
To fix my above issue, I've done these

1. Until it is added to the next beta ( #215 ) ,  manually add `!default` flag to `$sidebar-width` in your version's `custom-variables.scss` file

```css
// _custom-variables.scss
$sidebar-width:                     200px !default;
```

2. Then override the `$sidebar-width` variable in your scss file
```css
$sidebar-width: 220px;
```
3. To fix the `main` div being pushed to the right, when `sidebar` clicked on mobile
```css
// sidebar on the mobile, pushes the main div to the right when clicked
// fix it by setting up the margins to 0
.sidebar-mobile-show .main {
  margin-right: 0 !important;
  margin-left: 0 !important;
}
```
